name: practice_firebase_testing
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  firebase_auth: ^3.6.2
  cloud_firestore: ^3.1.7
  firebase_core: ^1.20.0
  sms_autofill: ^2.2.0
  # geolocator: ^9.0.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
